name: Deploy AWS
env: 
  NODE_VERSION: '14.x'
  S3_STAGING_URL: 'staging.imsc-visual-essay.allencell.org'
on:
  push:
    # Sequence of patterns matched against refs/tags
    branches:
      - main
    tags-ignore:
      # Do not run this job on commits matching v*, i.e. v1.0, v20.15.10,
      # since the staging S3 bucket should have been updated on merge to main
      # and re-deploying to staging at the same time as promoting to prod can
      # mess up the prod deployment
      - 'v*'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{env.NODE_VERSION}}
      - run: npm ci
      - run: npm run lint --if-present
  test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{env.NODE_VERSION}}
      - run: npm ci
      - run: npm test --if-present
  typeCheck:
    name: Type Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{env.NODE_VERSION}}
      - run: npm ci
      - run: npm run typeCheck --if-present
  deploy:
    needs: [lint, typeCheck, test]
    name: Upload to Amazon S3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{env.NODE_VERSION}}
      - run: npm ci 
      - run: npm run build
      - name: Remove all old files from staging bucket except those in assets/
        run: aws s3 rm s3://${{ env.S3_STAGING_URL }} --recursive --exclude "assets/*"
      - name: Update staging bucket with files in dist folder
        run: aws s3 sync ./dist/ s3://${{ env.S3_STAGING_URL }}
